name: Containerized API Platform (CAP) - Log Manager
description: |
  Containerized API Platform (CAP) - Simplified Log Manager 
version: cap-logmgr-v1
category: CAP Platform
maintainer: Elangovan Thinagaran
license: Apache
projectURL: https://github.com/telangovan/log.git
