name: Containerized API Platform (CAP) - Log Manager
description: |
  Containerized API Platform (CAP) - Simplified Log Manager 
version: cap-logmgr-v1
category: API Management Platform
maintainer: Venkateshwaran Subramanian
license: Apache
projectURL: http://bitbucket.org/dirosbit/apiplatform.git
